version: '3.3'
services:
  xmrig:
    image: rcmelendez/xmrig
    container_name: xmrig
    #environment:
    #  - TZ=America/New_York
    volumes:
      - ./config.json:/xmrig/etc/config.json:ro
      - ./log:/xmrig/log
    command: ["xmrig", "--config=/xmrig/etc/config.json"]
    restart: always
